### ISSUE TITLE
Rate limit corpus update

### ISSUE THREAD

**Issue by pyoor** [MozillaSecurity/guided-fuzzing-daemon#40]
```
Uploading reduced corpus to s3://mozilla-aflfuzz/jar-parser/corpus/
upload_corpus() -> before=2374, new=1732, deleted=1559, after=2547 (15.066s)
Running libFuzzer merge
Traceback (most recent call last):
  File "/usr/local/bin/guided-fuzzing-daemon", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/guided_fuzzing_daemon/main.py", line 122, in main
    return libfuzzer_main(opts, collector, storage)
  File "/usr/local/lib/python3.8/dist-packages/guided_fuzzing_daemon/libfuzzer.py", line 358, in libfuzzer_main
    assert not proc.wait()
  File "/usr/local/lib/python3.8/dist-packages/guided_fuzzing_daemon/storage.py", line 546, in __exit__
    corpus_uploader.delete_queues()
  File "/usr/local/lib/python3.8/dist-packages/guided_fuzzing_daemon/storage.py", line 428, in delete_queues
    self.provider.delete(existing)
  File "/usr/local/lib/python3.8/dist-packages/guided_fuzzing_daemon/storage.py", line 212, in delete
    keys = keys[1000:]
  File "/usr/lib/python3.8/contextlib.py", line 120, in __exit__
    next(self.gen)
  File "/usr/local/lib/python3.8/dist-packages/guided_fuzzing_daemon/utils.py", line 176, in Executor
    _check_jobs(final=True)
  File "/usr/local/lib/python3.8/dist-packages/guided_fuzzing_daemon/utils.py", line 153, in _check_jobs
    job.result()  # raises, if the job raised
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 437, in result
    return self.__get_result()
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.8/dist-packages/botocore/client.py", line 569, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/local/lib/python3.8/dist-packages/botocore/client.py", line 1023, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (SlowDown) when calling the DeleteObjects operation (reached max retries: 4): Please reduce your request rate.
```

**Comment by pyoor** [comment]
Closed via #41.
