### ISSUE TITLE
TypeError in download_corpus (guided_fuzzing_daemon/s3.py:442)

### ISSUE THREAD

**Issue by tysmith** [MozillaSecurity/guided-fuzzing-daemon#7]
```
Traceback (most recent call last):
  File "/usr/local/bin/guided-fuzzing-daemon", line 11, in <module>
    load_entry_point('guided-fuzzing-daemon==0.0.0', 'console_scripts', 'guided-fuzzing-daemon')()
  File "/usr/local/lib/python3.8/dist-packages/guided_fuzzing_daemon-0.0.0-py3.8.egg/guided_fuzzing_daemon/main.py", line 46, in main
    return s3_main(opts)
  File "/usr/local/lib/python3.8/dist-packages/guided_fuzzing_daemon-0.0.0-py3.8.egg/guided_fuzzing_daemon/s3.py", line 586, in s3_main
    s3m.download_corpus(opts.s3_corpus_download, opts.s3_corpus_download_size)
  File "/usr/local/lib/python3.8/dist-packages/guided_fuzzing_daemon-0.0.0-py3.8.egg/guided_fuzzing_daemon/s3.py", line 442, in download_corpus
    dest_file = corpus_dir / PurePosixPath(remote_key.name).name
TypeError: unsupported operand type(s) for /: 'str' and 'str'
```

**Comment by tysmith** [comment]
Looks like a simple typo `corpus_path` should be used not `corpus_dir`
